version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge